format_version: 10
pipelines:
  mypipeline:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-ce0f8ff:
        git: https://github.com/sholu/Juxaposition.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - dev:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          echome:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - hello
                command: echo
                run_if: passed
    parameters:
      hi: hello
